addons: 
  apt:
    packages: 
    - libboost-test-dev
compiler: clang
deploy: 
  provider: script
  script: 
    - curl -f -T CICppProject-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -unggshik:&BINTRAY_API_KEY \
    "https://api.bintray.com/content/nggshik/study-cpp/homework/&TRAVIS_BUILD_NUMBER/CICppProject-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;
     deb_distribution=xenial;
     deb_component=main;
     deb_architecture=amd64; 
     publish=1"
  skip_clenup: true
dist: xenial
language: cpp
script: 
  - "cmake ."
  - "cmake --build ."
  - "cmake --build . --target test"
  - "cmake --build . --target package"
