addons: 
  apt: 
    packages: 
      - libboost-test-dev
compiler: clang
deploy: 
  provider: script
  script: 
    - curl -f -T ci_cpp_project-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -unggshik:$BINTRAY_API_KEY "https://api.bintray.com/content/nggshik/study-cpp/homework/$TRAVIS_BUILD_NUMBER/ci_cpp_project-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=xenial;deb_component=main;deb_architecture=amd64"
  skip_clenup: true
dist: xenial
language: cpp
script: 
  - "cmake ."
  - "cmake --build ."
  - "cmake --build . --target test"
  - "cmake --build . --target package"
